### ISSUE TITLE
Error en distanceBoxtoBox

### ISSUE THREAD

**Issue by MarcoGirelaVida** [rbnuria/ParchisBoom#2]
Buenas de nuevo.
He identificado un error en la primera condición de la función "distanceBoxtoBox", linea 1692 de Parchis.cpp:
`    // Si mi pasillo está por medio es inalcanzable.
    if(ref_box1.num <= final_boxes.at(player) && final_boxes.at(player) < ref_box2.num){
        return -1;
    }
`
Cuando se está valorando una ficha que parte de la casilla donde comienzan las final boxes (por ejemplo, el verde en la casilla 68 al empezar la partida) y consultas la distancia con las fichas delante de él (por ejemplo el amarillo de la casilla 4) devuelve -1, cuando no es -1 puesto que, aunque el pasillo está "delante", como acaba de spawnear ignora el pasillo y sigue hacia delante.

Un saludo.

**Comment by jlsuarezdiaz** [comment]
Hola, no lo estoy entendiendo bien. Que el verde esté en la casilla 68 no debería ser problema, porque ese es el pasillo amarillo. Y si fuera la ficha amarilla, ya va hacia el pasillo sí o sí. Nunca va a ir hacia la casilla 1 la ficha amarilla. Puedes darme un ejemplo concreto y minimal en el que falle?

**Comment by MarcoGirelaVida** [comment]
Es cierto, perdón, olvidé cerrar el issue pero unas horas despúes me dí cuenta de que el puntero del box con el que estaba haciendo la llamada estaba apuntando donde no era, disculpe las molestian jajaja.
